apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
  namespace: osm-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiv2
  template:
    metadata:
      labels:
        app: apiv2
    spec:
      serviceAccountName: api-v2-service-account
      containers:
        - image: thorstenhans/osm-sample-api:0.2.0
          name: osm-sample-api
