apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-v1-service-account
  namespace: osm-sample-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-v2-service-account
  namespace: osm-sample-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: osm-sample-app