apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: osm-simple-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: osm-simple-app