name: Build and Push API v2 Image
on:
  push:
    branches: [ master ]
    paths: ['src/api-v2/*', 'dockerfiles/api-v2.Dockerfile']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: thorstenhans
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}
        repository: ${{ env.DOCKER_USER }}/osm-sample-api-v2
        tags: ci-latest, ci-${{ github.run_number }}
        tag_with_sha: true
        dockerfile: dockerfiles/api-v2.Dockerfile
        push: true
